<style>
@page{size:8.5in 13in;margin:.28in}.cibi-official-sheet{width:100%;border:.8pt solid #111;padding:.1in .15in .08in;font-family:DejaVu Sans,Arial,sans-serif;font-size:5.65pt;line-height:1.06}.cibi-official-sheet table{margin:0;border-collapse:collapse;table-layout:fixed}.cibi-official-sheet th,.cibi-official-sheet td{border:.55pt solid #111;padding:.02in .03in;vertical-align:middle;overflow-wrap:anywhere}.cibi-official-sheet th{background:#fff;font-size:5.15pt;font-weight:700}.cibi-official-header{display:table;width:100%;min-height:.48in;padding:.01in .03in .035in}.cibi-official-header>div,.cibi-official-header>img{display:table-cell;vertical-align:middle}.cibi-official-header>div{width:78%}.cibi-official-header img{width:1.35in;max-height:.4in;object-fit:contain}.cibi-title-line{display:table;width:100%}.cibi-title-line h1,.cibi-title-line strong{display:table-cell;margin:0;vertical-align:bottom}.cibi-title-line h1{font-size:9pt;line-height:1}.cibi-title-line strong{color:#1e3a8a;font-size:5.5pt;text-align:center}.cibi-scope{margin:.035in 0 0;font-size:5.4pt;font-style:italic}.cibi-confidential{margin:.05in 0 0;font-size:4.4pt;font-style:italic}.cibi-meta th{width:16%;border:0;padding:.02in .03in}.cibi-meta td{width:34%;height:.16in}.cibi-meta .cibi-options{border:0;font-size:5pt}.cibi-form-table{margin-top:.025in!important}.cibi-section-bar th{background:#d9d9d9;padding:.027in;font-size:6.6pt;text-align:center}.cibi-section-bar small{float:right;color:#b91c1c;font-size:4.4pt;font-style:italic;font-weight:400}.cibi-personal th{width:14%}.cibi-personal td{height:.145in}.cibi-options{font-size:4.75pt;white-space:normal}.cibi-purpose td{width:50%;height:.14in;font-size:5pt}.cibi-purpose th{width:16%}.cibi-grid-table th{background:#f2f2f2;text-align:center}.cibi-grid-table td{height:.15in;font-size:5.15pt}.cibi-grid-table thead tr:nth-child(2) th{font-size:4.6pt}.cibi-loans th:nth-child(8),.cibi-loans td:nth-child(8){width:24%}.cibi-summary{margin-top:.025in!important}.cibi-summary>tbody>tr>td{width:25%;border:0;padding:0 .025in 0 0;vertical-align:top}.cibi-summary>tbody>tr>td+td{width:75%;padding:0}.cibi-summary table th{width:78%}.cibi-summary table td{height:.17in}.cibi-income th:nth-child(1),.cibi-income td:nth-child(1){width:23%}.cibi-income th:nth-child(2),.cibi-income td:nth-child(2){width:36%}.cibi-income td{height:.18in}.cibi-signatures{margin-top:.025in!important}.cibi-signatures th{width:14%;border:0}.cibi-signatures td{width:36%;height:.3in;border:0;font-weight:700;text-align:center}.cibi-signatory-name{display:block;min-height:.075in}.cibi-signature-space{display:block;height:.075in}.cibi-signatures small{display:block;margin-top:.015in;font-size:4.6pt;font-weight:400;text-align:center}@media screen{.cibi-official-sheet{min-height:12.35in}}
.cibi-signatures small{font-size:5pt;font-weight:700;text-align:center}.cibi-official-sheet{min-height:0!important}
.cibi-signatures .cibi-prepared-by{height:auto;padding-top:.025in;padding-bottom:.025in}.cibi-prepared-by .cibi-signatory-name{min-height:0}.cibi-prepared-by small{margin-top:.012in}
.cibi-official-sheet .cibi-section-bar th{height:.18in;border:.55pt solid #111;background:#d9d9d9;color:#000;padding:.027in;font-family:DejaVu Sans,Arial,sans-serif;font-size:6.6pt;font-weight:700;line-height:1.06;text-align:left}
.cibi-other-remarks-row th{font-size:5.15pt;font-weight:400;white-space:nowrap}.cibi-other-remarks-row td{height:.145in;font-size:5.15pt;font-weight:400;white-space:nowrap;overflow:hidden}.cibi-purpose-remarks{margin:.025in 0 0;font-family:DejaVu Sans,Arial,sans-serif;font-size:5.15pt;font-weight:400}.cibi-purpose-remarks-box{width:100%;min-height:.22in;margin-top:.02in;border:.55pt solid #111;background:#fff;padding:.035in .045in;font-size:5.15pt;font-weight:400;line-height:1.2;white-space:pre-wrap;overflow-wrap:anywhere}
.cibi-purpose-guide{margin:.02in 0 .025in;font-family:DejaVu Sans,Arial,sans-serif;font-size:4.35pt;font-style:italic;font-weight:400;line-height:1.15;text-align:center;white-space:normal}
.cibi-banks .bank-institution{width:14%}.cibi-banks .bank-branch{width:10%}.cibi-banks .bank-year{width:8%}.cibi-banks .bank-adb{width:25%}.cibi-banks .bank-figures{width:5%}.cibi-banks .bank-capital{width:13%}.cibi-banks .bank-remarks{width:25%}.cibi-adb-print{font-size:4.2pt!important;white-space:nowrap}.cibi-adb-print span{margin-right:.012in}.cibi-adb-print em{font-style:normal}
.cibi-income-stability{font-size:4.35pt!important;line-height:1.2}.cibi-income-stability>div{display:flex;align-items:center;gap:.045in;white-space:nowrap}.cibi-income-stability>div+div{margin-top:.018in}.cibi-income-stability span{white-space:nowrap}
.cibi-section-iv-remarks{margin:.025in 0 0;font-family:DejaVu Sans,Arial,sans-serif;font-size:5.15pt;font-weight:400}.cibi-section-iv-remarks>span{display:block;margin-bottom:.02in}.cibi-section-iv-remarks-box{width:100%;min-height:.22in;border:.55pt solid #111;background:#fff;padding:.035in .045in;font-size:5.15pt;font-weight:400;line-height:1.2;white-space:pre-wrap;overflow-wrap:anywhere}
.cibi-section-iv-guide{margin:.02in 0 .025in;font-family:DejaVu Sans,Arial,sans-serif;font-size:4.35pt;font-style:italic;font-weight:400;line-height:1.15;text-align:center;white-space:normal}
</style>
