@php
    $cibi = $document['cibi']; $personal = $cibi['personal'];
    $na = fn ($value) => filled($value) ? $value : 'N/A';
    $choice = fn ($selected, $value, $label) => ($selected === $value ? '( ✓ ) ' : '(   ) ').$label;
    $purpose = fn ($code, $label) => (in_array($code, $cibi['purpose_codes'], true) ? '( ✓ ) ' : '(   ) ').$label;
    $checkMark = "\u{2713}";
    $choice = fn ($selected, $value, $label) => ($selected === $value ? "( {$checkMark} ) " : '(   ) ').$label;
    $purpose = fn ($code, $label) => (in_array($code, $cibi['purpose_codes'], true) ? "( {$checkMark} ) " : '(   ) ').$label;
    $bankRows = array_values(array_filter(
        array_slice($cibi['bank_accounts'], 0, 5),
        fn ($row) => collect($row)->contains(fn ($value) => filled($value) && $value !== 'N/A'),
    ));
    $loanRows = array_pad(array_slice($cibi['loan_records'], 0, 5), 5, array_fill(0, 8, ''));
    $incomeRows = array_values(array_slice($cibi['income_summaries'], 0, 3));
    $parseAdb = function ($value) use ($na): array {
        preg_match('/^(low|mid|high)(?:\s*\/\s*figures:\s*(.*))?$/i', (string) $value, $matches);

        return [
            strtolower($matches[1] ?? ''),
            filled($matches[2] ?? null) ? $matches[2] : (filled($matches[1] ?? null) ? 'N/A' : $na($value)),
        ];
    };
@endphp
<style>.cibi-choice-list{display:flex;flex-wrap:wrap;align-items:center;gap:.02in .09in}.cibi-choice-list span{white-space:nowrap}.cibi-section-bar.cibi-section-left th{text-align:left}.cibi-section-bar.cibi-section-left small{float:none;margin-left:.1in}.cibi-section-heading-line{white-space:nowrap}.cibi-section-title-detail{display:inline;margin-left:.035in;font:inherit}</style>
<article class="cibi-official-sheet" aria-label="Official BRBI Credit Investigation Report">
<header class="cibi-official-header"><div><div class="cibi-title-line"><h1>CREDIT INVESTIGATION REPORT</h1><strong>INDIVIDUAL ACCOUNT</strong></div><p class="cibi-scope">(RESULTS ON PERSONAL, NEIGHBORHOOD, RESIDENCE &amp; FINANCIAL INVESTIGATION)</p><p class="cibi-confidential">RESTRICTED &amp; CONFIDENTIAL</p></div><img src="{{ $pdfMode ? public_path('assets/branding/binhi-rural-bank-wordmark.png') : asset('assets/branding/binhi-rural-bank-wordmark.png') }}" alt="Binhi Rural Bank Inc."></header>
<table class="cibi-meta"><tbody>
<tr><th>CI-IN CHARGE:</th><td>{{ $cibi['ci_in_charge'] }}</td><th>BRANCH:</th><td>{{ $cibi['branch'] }}</td></tr>
<tr><th>START DATE OF CI:</th><td>{{ $cibi['start_date'] }}</td><th>ACCOUNT OFFICER:</th><td>{{ $cibi['account_officer'] }}</td></tr>
<tr><th>DATE SUBMITTED TO CA/BOO:</th><td>{{ $cibi['submitted_date'] }}</td><th>AMOUNT APPLIED:</th><td>{{ $cibi['amount_applied'] }}</td></tr>
<tr><td colspan="2" class="cibi-options"><div class="cibi-choice-list"><span>{{ $choice($cibi['party_type'], 'borrower', 'BORROWER') }}</span><span>{{ $choice($cibi['party_type'], 'co_maker', 'CO-MAKER') }}</span></div></td><th>CI RISK ASSESSMENT:</th><td class="cibi-options"><div class="cibi-choice-list">@foreach(['very_low'=>'VERY LOW','low'=>'LOW','mid'=>'MID','high'=>'HIGH','very_high'=>'VERY HIGH'] as $value=>$label)<span>{{ $choice($cibi['risk_level'], $value, $label) }}</span>@endforeach</div></td></tr>
</tbody></table>
<table class="cibi-form-table cibi-personal"><tbody>
<tr class="cibi-section-bar cibi-section-left"><th colspan="8">I. VALIDATED PERSONAL INFORMATION <small>(NOTE: All names shall be in "Last Name, First Name, Middle Name" format.)</small></th></tr>
<tr><th>NAME OF CLIENT:</th><td colspan="5">{{ $document['client_name'] }}</td><th>AGE:</th><td>{{ $na($personal['age'] ?? null) }}</td></tr>
<tr><th>SPOUSE'S NAME:</th><td colspan="5">{{ $na($personal['spouse_name'] ?? null) }}</td><th>AGE:</th><td>{{ $na($personal['spouse_age'] ?? null) }}</td></tr>
<tr><th>PRESENT ADDRESS:</th><td colspan="5">{{ $na($personal['present_address'] ?? null) }}</td><th>LENGTH OF STAY:</th><td>{{ $na($personal['length_of_stay_months'] ?? null) }}</td></tr>
<tr><td colspan="4" class="cibi-options"><div class="cibi-choice-list"><span>{{ $choice($personal['residence_status'] ?? null, 'Owned', 'OWNED') }}</span><span>{{ $choice($personal['residence_status'] ?? null, 'Mortgaged', 'MORTGAGED') }}</span><span>{{ $choice($personal['residence_status'] ?? null, 'Rented', 'RENTED') }}</span><span>{{ $choice($personal['residence_status'] ?? null, 'Living with Parents', 'LIVING WITH PARENTS') }}</span></div></td><th>FROM:</th><td>{{ $na($personal['residence_status_from'] ?? null) }}</td><th>MONTHLY RENT:</th><td>{{ $na($personal['monthly_rent'] ?? null) }}</td></tr>
<tr><th colspan="3">OTHER RESIDENCES (OWNED/MORTGAGED)</th><td colspan="5">{{ $na($personal['other_residences'] ?? null) }}</td></tr>
<tr><th>HOME CONDITION:</th><td colspan="3" class="cibi-options"><div class="cibi-choice-list">@foreach(['New','Slightly New','Ancestral','Apartment','Dorm','Shanty'] as $item)<span>{{ $choice($personal['home_condition'] ?? null, $item, strtoupper($item)) }}</span>@endforeach</div></td><th># OF STOREYS:</th><td colspan="3">{{ $na($personal['number_of_storeys'] ?? null) }}</td></tr>
<tr><th>MATERIAL COST:</th><td colspan="7" class="cibi-options"><div class="cibi-choice-list">@foreach(['Expensive','Medium','Low'] as $item)<span>{{ $choice($personal['material_cost_level'] ?? null, $item, strtoupper($item)) }}</span>@endforeach</div></td></tr>
<tr><th>LIVING CONDITION:</th><td colspan="7" class="cibi-options"><div class="cibi-choice-list">@foreach(['Excellent','Good','Poor'] as $item)<span>{{ $choice($personal['living_condition'] ?? null, $item, strtoupper($item)) }}</span>@endforeach</div></td></tr>
<tr><th>PREVIOUS ADDRESS:</th><td colspan="5">{{ $na($personal['previous_address'] ?? null) }}</td><th>LENGTH OF STAY:</th><td>{{ $na($personal['previous_address_length_of_stay_months'] ?? null) }}</td></tr>
<tr><th>PERMANENT ADDRESS:</th><td colspan="5">{{ $na($personal['parents_address'] ?? null) }}</td><th># OF DEPENDENTS:</th><td>{{ $na($personal['dependents_count'] ?? null) }}</td></tr>
<tr><th>CIVIL STATUS:</th><td colspan="5" class="cibi-options"><div class="cibi-choice-list">@foreach(['Single','Married','Separated','Divorced','Common Law','Widowed'] as $item)<span>{{ $choice($personal['civil_status'] ?? null, $item, strtoupper($item)) }}</span>@endforeach</div></td><th>IF SEPARATED, YEAR:</th><td>{{ $na($personal['separated_year'] ?? null) }}</td></tr>
<tr><th>REPUTATION:</th><td colspan="7" class="cibi-options"><div class="cibi-choice-list">@foreach(['Unknown'=>'UNKNOWN','Good'=>'GOOD','Rich'=>'RICH','Drunkard'=>'DRUNKARD','Adulterous'=>'ADULTEROUS','Gambler'=>'GAMBLER'] as $value=>$label)<span>{{ $choice($personal['reputation'] ?? null, $value, $label) }}</span>@endforeach<span>{{ in_array($personal['reputation'] ?? null, ['Heavily Indebted', 'Frequent Collector Visits'], true) ? '( ✓ ) ' : '(   ) ' }}HEAVILY INDEBTED/FREQUENT COLLECTOR VISITS</span></div></td></tr>
<tr><th>BRGY LEVEL FINDINGS:</th><td colspan="7" class="cibi-options"><div class="cibi-choice-list">@foreach(['N/A','No Legal Cases','With Legal Case'] as $item)<span>{{ $choice($personal['barangay_findings'] ?? null, $item, strtoupper($item)) }}</span>@endforeach</div></td></tr>
<tr><th>COURT BACKGROUND:</th><td colspan="7" class="cibi-options"><div class="cibi-choice-list">@foreach(['N/A','No Legal Cases','With Legal Case'] as $item)<span>{{ $choice($personal['court_background_status'] ?? null, $item, strtoupper($item)) }}</span>@endforeach</div></td></tr>
<tr><th>LIFESTYLE:</th><td colspan="3" class="cibi-options"><div class="cibi-choice-list">@foreach(['Modest','Extravagant','Below Average'] as $item)<span>{{ $choice($personal['lifestyle'] ?? null, $item, strtoupper($item)) }}</span>@endforeach</div></td><th>VEHICLES OWNED:</th><td colspan="3">{{ $na($personal['vehicles_owned'] ?? null) }}</td></tr>
<tr><th colspan="2">VALIDATED CONTACT NUMBER(S)/EMAIL:</th><td colspan="6">{{ $na($personal['contact_details'] ?? null) }}</td></tr><tr class="cibi-other-remarks-row"><th>OTHER REMARKS:</th><td colspan="7">{{ $na($personal['other_remarks'] ?? null) }}</td></tr>
</tbody></table>
<table class="cibi-form-table cibi-purpose"><tbody><tr class="cibi-section-bar cibi-section-left"><th colspan="2">II. VALIDATED PURPOSE FOR LOAN APPLICATION</th></tr>
<tr><td>{{ $purpose('working_capital', 'WORKING CAPITAL (INVENTORY/RECEIVABLES)') }}</td><td>{{ $purpose('business_expansion', 'BUSINESS EXPANSION: RENOVATION / START UP INVENTORY') }}</td></tr><tr><td>{{ $purpose('buyout_debt_consolidation', 'BUYOUT/DEBT CONSOLIDATION') }}</td><td>{{ $purpose('chattel_property_acquisition', 'CHATTEL PROPERTY ACQUISITION') }}</td></tr><tr><td>{{ $purpose('building_construction_home_renovation', 'BUILDING CONSTRUCTION / HOME RENOVATION') }}</td><td>{{ $purpose('real_estate_property_acquisition', 'REAL ESTATE PROPERTY ACQUISITION') }}</td></tr><tr><td>{{ $purpose('personal', 'PERSONAL: MEDICAL EXPENSES / EDUCATION / TRAVEL / ESTATE MGT') }}</td><td>{{ $purpose('others', 'OTHERS') }}</td></tr></tbody></table>
<div class="cibi-purpose-remarks"><span>OTHER REMARKS:</span><div class="cibi-purpose-remarks-box">{{ $cibi['purpose_remarks'] }}</div></div>
<p class="cibi-purpose-guide">EXAMPLE: SELLER OR SUPPLIER OF CHATTEL OR REAL ESTATE TO BE ACQUIRED / LOAN FOR BUYOUT IS PAST DUE / AMOUNT APPLIED IS SO MUCH HIGHER THAN AMOUNT REQUIRED FOR PURPOSE</p>
<table class="cibi-form-table cibi-grid-table cibi-banks"><colgroup><col class="bank-institution"><col class="bank-branch"><col class="bank-year"><col class="bank-adb"><col class="bank-figures"><col class="bank-capital"><col class="bank-remarks"></colgroup><thead><tr class="cibi-section-bar cibi-section-left"><th colspan="7"><span class="cibi-section-heading-line">III. BANK / FINANCIAL INSTITUTION</span></th></tr><tr><th>BANK/FINANCIAL INSTITUTION</th><th>BRANCH</th><th>YEAR OPENED</th><th colspan="2">ADB LEVEL</th><th>CA/SA/SHARE CAPITAL</th><th>RELEVANT REMARKS</th></tr></thead><tbody>@foreach($bankRows as $row) @php([$adbLevel, $adbFigures] = $parseAdb($row[3] ?? null))<tr><td>{{ $row[0] }}</td><td>{{ $row[1] }}</td><td>{{ $row[2] }}</td><td class="cibi-adb-print"><span>{{ $choice($adbLevel, 'low', 'LOW') }}</span><span>{{ $choice($adbLevel, 'mid', 'MID') }}</span><span>{{ $choice($adbLevel, 'high', 'HIGH') }}</span><em>/ FIGURES:</em></td><td>{{ $adbFigures }}</td><td>{{ $row[4] }}</td><td>{{ $row[5] }}</td></tr>@endforeach</tbody></table>
<table class="cibi-form-table cibi-grid-table cibi-loans"><thead><tr class="cibi-section-bar cibi-section-left"><th colspan="8"><span class="cibi-section-heading-line">IV. SUMMARY ON CREDIT/LOAN INFORMATION <span class="cibi-section-title-detail">(BANKS, COOPERATIVES, LENDING INSTITUTIONS)</span></span></th></tr><tr><th>BANK/COOP/BRANCH</th><th>ORIGINAL AMOUNT</th><th>REMAINING BALANCE</th><th>AMORTIZATION AMOUNT</th><th>DATE GRANTED - MATURITY DATE</th><th>CYCLE NO.</th><th>TYPE OF SECURITY</th><th>PAYMENT PERFORMANCE &amp; OTHER FINDINGS</th></tr></thead><tbody>@foreach($loanRows as $row)<tr>@foreach($row as $value)<td>{{ $value }}</td>@endforeach</tr>@endforeach</tbody></table>
<table class="cibi-summary"><tbody><tr><td class="cibi-totals"><table><tr><th>TOTAL # OF INSTITUTIONS CHECKED:</th><td>{{ $cibi['totals']['checked'] }}</td></tr><tr><th>TOTAL # OF INSTITUTIONS DECLARED:</th><td>{{ $cibi['totals']['declared'] }}</td></tr><tr><th>TOTAL # OF LOAN RECORDS FOUND:</th><td>{{ $cibi['totals']['loans'] }}</td></tr></table></td><td><table><tr><th>REASONS FOR NEGATIVE FINDINGS ON CREDIT PERFORMANCE:</th></tr><tr><td>{{ $cibi['negative_credit_findings'] }}</td></tr></table></td></tr></tbody></table>
<div class="cibi-section-iv-remarks"><span>OTHER REMARKS:</span><div class="cibi-section-iv-remarks-box">{{ $cibi['other_remarks'] }}</div></div>
<p class="cibi-section-iv-guide">EXAMPLE: FREQUENT COLLECTOR VISITS / OFF HAND VALIDATION THAT CLIENT HAS SEVERAL PENDING LOAN APPLICATIONS</p>
<table class="cibi-form-table cibi-grid-table cibi-income"><thead><tr class="cibi-section-bar cibi-section-left"><th colspan="3"><span class="cibi-section-heading-line">V. INCOME SOURCES VALIDATION <span class="cibi-section-title-detail">(ATTACH DETAILED REPORT WITH PICTURES)</span></span></th></tr><tr><th>INCOME SOURCES VALIDATED</th><th>STABILITY OF INCOME SOURCE</th><th>KEY/RELEVANT INFORMATION GATHERED</th></tr></thead><tbody>@foreach($incomeRows as $row)<tr><td>{{ $row[0] }}</td><td class="cibi-income-stability"><div><span>{{ $choice($row[1] ?? null, 'existing_strong_capacity', 'EXISTING WITH STRONG CAPACITY') }}</span><span>{{ $choice($row[1] ?? null, 'existing_weak_capacity', 'EXISTING BUT WEAK CAPACITY') }}</span></div><div><span>{{ $choice($row[1] ?? null, 'not_validated', 'WAS NOT/CANNOT BE VALIDATED') }}</span></div></td><td>{{ $row[2] }}</td></tr>@endforeach</tbody></table>
<table class="cibi-signatures"><tbody><tr><th>PREPARED BY:</th><td class="cibi-prepared-by"><span class="cibi-signatory-name">{{ $cibi['prepared_by'] }}</span><small>CREDIT INVESTIGATOR</small></td><th>NOTED BY:</th><td><span class="cibi-signatory-name">{{ $cibi['noted_by'] === 'N/A' ? '' : $cibi['noted_by'] }}</span><span class="cibi-signature-space" aria-hidden="true"></span><small>CA1</small></td></tr></tbody></table>
</article>
