<section id="header-section" class="cibi-paper-section scroll-mt-24" aria-labelledby="cibi-official-title">
    <div class="cibi-excel-heading">
        <div><h1 id="cibi-official-title">Credit Investigation Report</h1><p class="cibi-account-type">Individual Account</p><p class="cibi-investigation-scope">(Results on Personal, Neighborhood, Residence &amp; Financial Investigation)</p><p class="cibi-confidentiality">Restricted &amp; Confidential</p></div>
        <img src="{{ asset('assets/branding/binhi-rural-bank-wordmark.png') }}" alt="Binhi Rural Bank Inc." class="h-auto w-40 shrink-0 object-contain sm:w-44">
    </div>
    <div class="cibi-excel-metadata mt-3 grid sm:grid-cols-2">
        <div><span class="ui-label">CI-In Charge</span><p class="cibi-readonly-field">{{ $report?->investigator?->full_name ?? $clientFolder->assignedInvestigator->full_name }}</p></div>
        <x-form.input name="branch_name" label="Branch" :value="$report?->branch_name" required />
        <x-form.input name="start_date" label="Start Date of CI" type="date" :value="$report?->start_date?->format('Y-m-d')" required />
        <x-form.input name="account_officer_name" label="Account Officer" :value="$report?->account_officer_name" required />
        <x-form.input name="submitted_date" label="Date Submitted to CA / BOO" type="date" :value="$report?->submitted_date?->format('Y-m-d')" required />
        <x-form.input name="amount_applied" label="Amount Applied" type="text" inputmode="decimal" :value="$report?->amount_applied" data-number-format />
        <fieldset><legend class="ui-label">Borrower / Co-Maker <span class="text-danger" aria-hidden="true">*</span><span class="sr-only">required</span></legend><div class="flex min-h-10 flex-wrap items-center gap-x-4 gap-y-2">@foreach($partyTypes as $type)<label class="inline-flex cursor-pointer items-center gap-1.5 text-sm font-medium"><input type="radio" name="party_type" value="{{ $type->value }}" @checked(old('party_type', $report?->party_type?->value ?? 'borrower') === $type->value) required class="size-4 border-ui-border-strong text-brand-primary focus:ring-brand-primary">{{ str($type->value)->replace('_', ' ')->title() }}</label>@endforeach</div><x-form.validation-message for="party_type" /></fieldset>
        <fieldset><legend class="ui-label">CI Risk Assessment <span class="text-danger" aria-hidden="true">*</span><span class="sr-only">required</span></legend><div class="flex min-h-10 flex-wrap items-center gap-x-3 gap-y-2">@foreach(['very_low' => 'Very Low', 'low' => 'Low', 'mid' => 'Mid', 'high' => 'High', 'very_high' => 'Very High'] as $value => $label)<label class="inline-flex cursor-pointer items-center gap-1.5 text-xs font-medium"><input type="radio" name="ci_risk_level" value="{{ $value }}" @checked(old('ci_risk_level', $report?->ci_risk_level) === $value) required class="size-4 border-ui-border-strong text-brand-primary focus:ring-brand-primary">{{ $label }}</label>@endforeach</div><x-form.validation-message for="ci_risk_level" /></fieldset>
    </div>
</section>

<section id="client-source-section" class="cibi-paper-section scroll-mt-24" aria-labelledby="validated-personal-title" data-cibi-personal-fields>
    <div class="cibi-section-heading cibi-personal-heading"><h2 id="validated-personal-title">I. Validated Personal Information</h2><p>(Note: All names shall be in "Last Name, First Name, Middle Name" format.)</p></div>
    <div class="cibi-excel-grid grid sm:grid-cols-2 lg:grid-cols-3">
        <div class="sm:col-span-2"><label for="personal-snapshot-name-display" class="ui-label">Name of Client</label><input id="personal-snapshot-name-display" value="{{ $clientFolder->display_name }}" class="ui-control bg-surface-muted" readonly aria-readonly="true"><input type="hidden" name="personal_snapshot[name]" value="{{ $clientFolder->display_name }}"><x-form.validation-message for="personal_snapshot.name" /></div>
        <x-form.input name="personal_snapshot.age" input-name="personal_snapshot[age]" label="Age" type="number" min="0" max="150" :value="data_get($personalSnapshot, 'age')" required />
        <x-form.input name="personal_snapshot.spouse_name" input-name="personal_snapshot[spouse_name]" label="Spouse's Name" :value="data_get($personalSnapshot, 'spouse_name')" class="sm:col-span-2" required />
        <x-form.input name="personal_snapshot.spouse_age" input-name="personal_snapshot[spouse_age]" label="Spouse Age" type="number" min="0" max="150" :value="data_get($personalSnapshot, 'spouse_age')" required />
        <x-form.textarea name="personal_snapshot.present_address" input-name="personal_snapshot[present_address]" label="Present Address" :value="data_get($personalSnapshot, 'present_address')" rows="3" class="sm:col-span-2 lg:col-span-3" data-present-address required />
        <fieldset class="sm:col-span-2 lg:col-span-3"><legend class="sr-only">Residence Status and rental details</legend><div class="grid gap-3 rounded-control border border-ui-border bg-surface-subtle p-3 sm:grid-cols-2 lg:grid-cols-3 lg:items-end">
            <div class="min-w-0"><label for="personal-residence-status" class="ui-label">Residence Status <span class="text-danger" aria-hidden="true">*</span><span class="sr-only">required</span></label><select id="personal-residence-status" name="personal_snapshot[residence_status]" class="ui-control" data-residence-status required><option value="">Select Status</option>@foreach(['Owned', 'Mortgaged', 'Rented', 'Living with Parents'] as $status)<option value="{{ $status }}" @selected(data_get($personalSnapshot, 'residence_status') === $status)>{{ $status }}</option>@endforeach</select></div>
            <div class="min-w-0 flex-1"><label for="personal-residence-from" class="ui-label">From</label><input id="personal-residence-from" class="ui-control" value="{{ data_get($personalSnapshot, 'residence_status_from') }}" data-residence-from-display><input type="hidden" name="personal_snapshot[residence_status_from]" value="{{ data_get($personalSnapshot, 'residence_status_from') }}" data-residence-from-value><x-form.validation-message for="personal_snapshot.residence_status_from" /></div>
            <div class="min-w-0 flex-1"><label for="personal-monthly-rent" class="ui-label">Monthly Rent</label><input id="personal-monthly-rent" class="ui-control" value="{{ data_get($personalSnapshot, 'monthly_rent') }}" data-monthly-rent-display><input type="hidden" name="personal_snapshot[monthly_rent]" value="{{ data_get($personalSnapshot, 'monthly_rent') }}" data-monthly-rent-value><x-form.validation-message for="personal_snapshot.monthly_rent" /></div>
        </div><x-form.validation-message for="personal_snapshot.residence_status" /></fieldset>
        <x-form.input name="personal_snapshot.length_of_stay_months" input-name="personal_snapshot[length_of_stay_months]" label="Length of Stay" :value="data_get($personalSnapshot, 'length_of_stay_months')" placeholder="e.g. 12 years" />
        <div class="sm:col-span-2"><label for="personal-other-residences" class="ui-label">OTHER RESIDENCES (OWNED/MORTGAGED)</label><input id="personal-other-residences" name="personal_snapshot[other_residences]" class="ui-control" value="{{ data_get($personalSnapshot, 'other_residences') }}"><x-form.validation-message for="personal_snapshot.other_residences" /></div>
        <x-form.select name="personal_snapshot.home_condition" input-name="personal_snapshot[home_condition]" label="Home Condition" :options="['New' => 'New', 'Slightly New' => 'Slightly New', 'Ancestral' => 'Ancestral', 'Apartment' => 'Apartment', 'Dorm' => 'Dorm', 'Shanty' => 'Shanty', 'Other' => 'Other']" :selected="data_get($personalSnapshot, 'home_condition')" placeholder="Select condition" required />
        <x-form.input name="personal_snapshot.number_of_storeys" input-name="personal_snapshot[number_of_storeys]" label="Number of Storeys" type="number" min="0" max="100" :value="data_get($personalSnapshot, 'number_of_storeys')" required />
        <x-form.select name="personal_snapshot.material_cost_level" input-name="personal_snapshot[material_cost_level]" label="Material Cost" :options="['Expensive' => 'Expensive', 'Medium' => 'Medium', 'Low' => 'Low']" :selected="data_get($personalSnapshot, 'material_cost_level')" placeholder="Select level" required />
        <x-form.select name="personal_snapshot.living_condition" input-name="personal_snapshot[living_condition]" label="Living Condition" :options="['Excellent' => 'Excellent', 'Good' => 'Good', 'Poor' => 'Poor']" :selected="data_get($personalSnapshot, 'living_condition')" placeholder="Select condition" required />
        <div class="sm:col-span-2 lg:col-span-3"><label for="personal-previous-address" class="ui-label">Previous Address</label><textarea id="personal-previous-address" name="personal_snapshot[previous_address]" rows="3" class="ui-control">{{ data_get($personalSnapshot, 'previous_address') }}</textarea><button type="button" class="cibi-address-suggestion" data-copy-present-address="personal-previous-address" aria-label="Use Present Address for Previous Address" hidden><span class="cibi-address-suggestion-title">Use Present Address</span><span data-present-address-suggestion></span></button><x-form.validation-message for="personal_snapshot.previous_address" /></div>
        <x-form.input name="personal_snapshot.previous_address_length_of_stay_months" input-name="personal_snapshot[previous_address_length_of_stay_months]" label="Previous Address Length of Stay" :value="data_get($personalSnapshot, 'previous_address_length_of_stay_months')" placeholder="e.g. 5 years" />
        <div class="sm:col-span-2 lg:col-span-3"><label for="personal-permanent-address" class="ui-label">Permanent Address <span class="text-danger" aria-hidden="true">*</span><span class="sr-only">required</span></label><textarea id="personal-permanent-address" name="personal_snapshot[parents_address]" rows="3" class="ui-control" required>{{ data_get($personalSnapshot, 'parents_address') }}</textarea><button type="button" class="cibi-address-suggestion" data-copy-present-address="personal-permanent-address" aria-label="Use Present Address for Permanent Address" hidden><span class="cibi-address-suggestion-title">Use Present Address</span><span data-present-address-suggestion></span></button><x-form.validation-message for="personal_snapshot.parents_address" /></div>
        <x-form.input name="personal_snapshot.dependents_count" input-name="personal_snapshot[dependents_count]" label="Number of Dependents" type="number" min="0" max="100" :value="data_get($personalSnapshot, 'dependents_count')" />
        <x-form.select name="personal_snapshot.civil_status" input-name="personal_snapshot[civil_status]" label="Civil Status" :options="['Single' => 'Single', 'Married' => 'Married', 'Separated' => 'Separated', 'Divorced' => 'Divorced', 'Common Law' => 'Common Law', 'Widowed' => 'Widowed']" :selected="data_get($personalSnapshot, 'civil_status')" placeholder="Select status" required />
        <x-form.input name="personal_snapshot.separated_year" input-name="personal_snapshot[separated_year]" label="Separated Year" :value="data_get($personalSnapshot, 'separated_year')" placeholder="e.g. 2018" />
        <x-form.select name="personal_snapshot.reputation" input-name="personal_snapshot[reputation]" label="Reputation" :options="['Unknown' => 'Unknown', 'Good' => 'Good', 'Rich' => 'Rich', 'Drunkard' => 'Drunkard', 'Adulterous' => 'Adulterous', 'Gambler' => 'Gambler', 'Heavily Indebted' => 'Heavily Indebted', 'Frequent Collector Visits' => 'Frequent Collector Visits']" :selected="data_get($personalSnapshot, 'reputation')" placeholder="Select finding" required />
        <x-form.select name="personal_snapshot.barangay_findings" input-name="personal_snapshot[barangay_findings]" label="Barangay Level Findings" :options="['N/A' => 'N/A', 'No Legal Cases' => 'No Legal Cases', 'With Legal Case' => 'With Legal Case']" :selected="data_get($personalSnapshot, 'barangay_findings')" placeholder="Select finding" required />
        <x-form.select name="personal_snapshot.court_background_status" input-name="personal_snapshot[court_background_status]" label="Court Background" :options="['N/A' => 'N/A', 'No Legal Cases' => 'No Legal Cases', 'With Legal Case' => 'With Legal Case']" :selected="data_get($personalSnapshot, 'court_background_status')" placeholder="Select finding" />
        <x-form.select name="personal_snapshot.lifestyle" input-name="personal_snapshot[lifestyle]" label="Lifestyle" :options="['Modest' => 'Modest', 'Extravagant' => 'Extravagant', 'Below Average' => 'Below Average']" :selected="data_get($personalSnapshot, 'lifestyle')" placeholder="Select lifestyle" required />
        <x-form.textarea name="personal_snapshot.vehicles_owned" input-name="personal_snapshot[vehicles_owned]" label="Vehicles Owned" :value="data_get($personalSnapshot, 'vehicles_owned')" rows="2" />
        <x-form.input name="personal_snapshot.contact_details" input-name="personal_snapshot[contact_details]" label="Validated Contact Number(s) / Email" :value="data_get($personalSnapshot, 'contact_details')" class="sm:col-span-2" />
        <x-form.input name="personal_snapshot.other_remarks" input-name="personal_snapshot[other_remarks]" label="Other Remarks" :value="data_get($personalSnapshot, 'other_remarks')" class="cibi-inline-remarks sm:col-span-2 lg:col-span-3" />
        <input type="hidden" name="personal_snapshot[living_with_parents]" value="{{ data_get($personalSnapshot, 'living_with_parents', false) ? 1 : 0 }}"><input type="hidden" name="personal_snapshot[court_background]" value="{{ data_get($personalSnapshot, 'court_background', 'N/A') }}">
    </div>
</section>

<section id="purpose-section" class="cibi-paper-section scroll-mt-24"><div class="cibi-section-heading"><h2>II. Validated Purpose for Loan Application</h2></div><div class="cibi-excel-grid grid sm:grid-cols-2"><x-form.choice-group name="purpose_codes" label="Validated Purpose" :options="$purposeOptions" :selected="$report?->purpose_codes ?? []" :hover="false" :columns="2" class="cibi-purpose-grid sm:col-span-2" /><x-form.textarea name="purpose_remarks" label="Other Remarks" :value="$report?->purpose_remarks" class="sm:col-span-2" rows="3" /></div></section>

@include('client-folders.cibi-report._official-table', ['section' => 'bank_accounts', 'title' => 'III. Bank / Financial Institution', 'addLabel' => 'Add Bank', 'records' => $report?->bankAccounts ?? collect()])
@include('client-folders.cibi-report._official-table', ['section' => 'loan_records', 'title' => 'IV. Summary on Credit / Loan Information', 'addLabel' => 'Add Loan', 'records' => $report?->loanRecords ?? collect()])

<section class="cibi-paper-section" aria-label="Credit and loan totals"><div class="cibi-excel-grid grid sm:grid-cols-3"><x-form.input name="summary_totals.institutions_checked" input-name="summary_totals[institutions_checked]" label="Total # of Institutions Checked" type="number" min="0" :value="data_get($summaryTotals, 'institutions_checked', 0)" data-cibi-total="checked" /><x-form.input name="summary_totals.institutions_declared" input-name="summary_totals[institutions_declared]" label="Total # of Institutions Declared" type="number" min="0" :value="data_get($summaryTotals, 'institutions_declared', 0)" data-cibi-total="declared" /><x-form.input name="summary_totals.loan_records_found" input-name="summary_totals[loan_records_found]" label="Total # of Loan Records Found" type="number" min="0" :value="data_get($summaryTotals, 'loan_records_found', 0)" data-cibi-total="loans" /><x-form.textarea name="negative_credit_findings" label="Reasons for Negative Findings on Credit Performance" :value="$report?->negative_credit_findings" rows="4" class="sm:col-span-2" /><x-form.textarea name="other_remarks" label="Other Remarks" :value="$report?->other_remarks" rows="4" class="sm:col-span-3" /></div></section>

@include('client-folders.cibi-report._official-table', ['section' => 'income_summaries', 'title' => 'V. Income Sources Validation', 'addLabel' => 'Add Income Source', 'records' => $report?->incomeSourceSummaries ?? collect()])

<section id="remarks-section" class="cibi-paper-section cibi-signatories scroll-mt-24"><div class="cibi-excel-grid grid sm:grid-cols-2"><div class="cibi-prepared-by"><span class="ui-label">Prepared By</span><p class="cibi-encoding-signatory-name" aria-label="Prepared by Credit Investigator">{{ $report?->investigator?->full_name ?? $clientFolder->assignedInvestigator->full_name }}</p><input type="hidden" name="prepared_by_name" value="{{ $report?->investigator?->full_name ?? $clientFolder->assignedInvestigator->full_name }}"><p class="cibi-signatory-role">CREDIT INVESTIGATOR</p></div><div><label for="noted_by_name" class="ui-label">Noted By</label><input id="noted_by_name" name="noted_by_name" value="{{ old('noted_by_name', $report?->noted_by_name) }}" class="ui-control bg-surface-muted" readonly aria-readonly="true"><x-form.validation-message for="noted_by_name" /><p class="cibi-signatory-role">CA1</p></div></div></section>
