@php $prefix = "{$section}[{$index}]"; $id = data_get($row, 'id'); @endphp
<tr data-repeater-row @if(data_get($row, '_delete')) hidden @endif>
@if($section === 'bank_accounts')
    <td><input type="hidden" name="{{ $prefix }}[id]" value="{{ $id }}"><input type="hidden" name="{{ $prefix }}[_delete]" value="0" data-delete-field><input aria-label="Institution" name="{{ $prefix }}[institution]" value="{{ data_get($row, 'institution') }}" class="ui-control"></td><td><input aria-label="Branch" name="{{ $prefix }}[branch]" value="{{ data_get($row, 'branch') }}" class="ui-control"></td><td><input aria-label="Year opened" type="number" name="{{ $prefix }}[year_opened]" value="{{ data_get($row, 'year_opened') }}" class="ui-control w-24"></td>
    <td><div class="cibi-adb-controls text-xs"><div class="cibi-adb-choice-line">@foreach(['low'=>'LOW','mid'=>'MID','high'=>'HIGH'] as $value=>$label)<label><input type="radio" name="{{ $prefix }}[adb_level_choice]" value="{{ $value }}" @checked(data_get($row, 'adb_level_choice') === $value) data-adb-choice>{{ $label }}</label>@endforeach<span>/ FIGURES:</span><input id="adb-figures-{{ $section }}-{{ $index }}" aria-label="ADB figures" name="{{ $prefix }}[adb_level_figures]" value="{{ data_get($row, 'adb_level_figures') }}" placeholder="Figures" class="ui-control cibi-compact-financial-input" data-adb-figures></div></div></td>
    <td><input aria-label="CA SA or share capital" name="{{ $prefix }}[capital_share_text]" value="{{ data_get($row, 'capital_share_text') }}" class="ui-control cibi-compact-financial-input"><input type="hidden" name="{{ $prefix }}[capital_share_amount]" value="{{ data_get($row, 'capital_share_amount') }}"></td><td><textarea aria-label="Relevant remarks" name="{{ $prefix }}[relevant_remarks]" rows="2" class="ui-control">{{ data_get($row, 'relevant_remarks') }}</textarea></td>
@else
    <td><input type="hidden" name="{{ $prefix }}[id]" value="{{ $id }}"><input type="hidden" name="{{ $prefix }}[_delete]" value="0" data-delete-field><input type="hidden" name="{{ $prefix }}[income_source_id]" value="{{ data_get($row, 'income_source_id') }}"><input aria-label="Income source validated" name="{{ $prefix }}[source_name]" value="{{ data_get($row, 'source_name') }}" class="ui-control"><input type="hidden" name="{{ $prefix }}[source_type]" value="{{ data_get($row, 'source_type') }}"><input type="hidden" name="{{ $prefix }}[validation_status]" value="{{ data_get($row, 'validation_status') }}"><input type="hidden" name="{{ $prefix }}[monthly_amount]" value="{{ data_get($row, 'monthly_amount') }}"></td><td><div class="space-y-0.5 text-[0.68rem] leading-tight">@foreach(['existing_strong_capacity'=>'EXISTING WITH STRONG CAPACITY','existing_weak_capacity'=>'EXISTING BUT WEAK CAPACITY','not_validated'=>'WAS NOT / CANNOT BE VALIDATED'] as $value=>$label)<label class="flex items-start gap-1"><input type="radio" name="{{ $prefix }}[stability_result]" value="{{ $value }}" @checked(data_get($row, 'stability_result') === $value) class="mt-0.5 size-3">{{ $label }}</label>@endforeach</div></td><td><textarea aria-label="Key information" name="{{ $prefix }}[key_information]" rows="2" class="ui-control">{{ data_get($row, 'key_information') }}</textarea></td>
@endif
<td class="cibi-entry-action-cell"><button type="button" class="cibi-remove-entry-button" title="Remove entry" aria-label="Remove entry" data-repeater-remove><x-ui.icon name="trash" size="size-5" /></button></td></tr>
