@php $prefix = "{$section}[{$index}]"; $id = data_get($row, 'id'); @endphp
<tr data-repeater-row @if(data_get($row, '_delete')) hidden @endif>
@if($section === 'bank_accounts')
    <td><input type="hidden" name="{{ $prefix }}[id]" value="{{ $id }}"><input type="hidden" name="{{ $prefix }}[_delete]" value="0" data-delete-field><input aria-label="Institution" name="{{ $prefix }}[institution]" value="{{ data_get($row, 'institution') }}" class="ui-control"></td><td><input aria-label="Branch" name="{{ $prefix }}[branch]" value="{{ data_get($row, 'branch') }}" class="ui-control"></td><td><input aria-label="Year opened" type="number" name="{{ $prefix }}[year_opened]" value="{{ data_get($row, 'year_opened') }}" class="ui-control w-24"></td>
    <td><div class="cibi-adb-controls text-xs"><div class="cibi-adb-choice-line">@foreach(['low'=>'LOW','mid'=>'MID','high'=>'HIGH'] as $value=>$label)<label><input type="radio" name="{{ $prefix }}[adb_level_choice]" value="{{ $value }}" @checked(data_get($row, 'adb_level_choice') === $value) data-adb-choice>{{ $label }}</label>@endforeach<span>/ FIGURES:</span><input id="adb-figures-{{ $section }}-{{ $index }}" aria-label="ADB figures" name="{{ $prefix }}[adb_level_figures]" value="{{ data_get($row, 'adb_level_figures') }}" placeholder="Figures" class="ui-control cibi-compact-financial-input" data-adb-figures></div></div></td>
    <td><input aria-label="CA SA or share capital" name="{{ $prefix }}[capital_share_text]" value="{{ data_get($row, 'capital_share_text') }}" class="ui-control cibi-compact-financial-input"><input type="hidden" name="{{ $prefix }}[capital_share_amount]" value="{{ data_get($row, 'capital_share_amount') }}"></td><td><textarea aria-label="Relevant remarks" name="{{ $prefix }}[relevant_remarks]" rows="2" class="ui-control">{{ data_get($row, 'relevant_remarks') }}</textarea></td>
@elseif($section === 'loan_records')
    <td><input type="hidden" name="{{ $prefix }}[id]" value="{{ $id }}"><input type="hidden" name="{{ $prefix }}[_delete]" value="0" data-delete-field><input aria-label="Bank cooperative or branch" name="{{ $prefix }}[institution]" value="{{ data_get($row, 'institution') }}" class="ui-control"></td>@foreach(['original_amount'=>'Original amount','remaining_balance'=>'Remaining balance','amortization_amount'=>'Amortization amount'] as $field=>$label)<td><input aria-label="{{ $label }}" name="{{ $prefix }}[{{ $field }}]" value="{{ data_get($row, $field) }}" inputmode="decimal" class="ui-control cibi-loan-amount-input" data-number-format></td>@endforeach
    <td><div class="cibi-loan-date-controls"><input aria-label="Granted date" title="Granted Date" type="date" name="{{ $prefix }}[granted_date]" value="{{ data_get($row, 'granted_date') ? Illuminate\Support\Carbon::parse(data_get($row, 'granted_date'))->format('Y-m-d') : '' }}" class="ui-control cibi-compact-date-input"><input aria-label="Maturity date" title="Maturity Date" type="date" name="{{ $prefix }}[maturity_date]" value="{{ data_get($row, 'maturity_date') ? Illuminate\Support\Carbon::parse(data_get($row, 'maturity_date'))->format('Y-m-d') : '' }}" class="ui-control cibi-compact-date-input"></div></td>
    <td><div class="cibi-loan-meta-controls"><input aria-label="Cycle number" name="{{ $prefix }}[cycle_label]" value="{{ data_get($row, 'cycle_label') }}" placeholder="Cycle No." class="ui-control cibi-cycle-input"><input aria-label="Type of security" name="{{ $prefix }}[security_type]" value="{{ data_get($row, 'security_type') }}" placeholder="Security" class="ui-control cibi-security-input"><input type="hidden" name="{{ $prefix }}[cycle_number]" value="{{ data_get($row, 'cycle_number') }}"></div></td><td><textarea aria-label="Payment performance and relevant findings" name="{{ $prefix }}[combined_findings]" rows="4" class="ui-control">{{ data_get($row, 'combined_findings') }}</textarea></td>
@else
    <td><input type="hidden" name="{{ $prefix }}[id]" value="{{ $id }}"><input type="hidden" name="{{ $prefix }}[_delete]" value="0" data-delete-field><input type="hidden" name="{{ $prefix }}[income_source_id]" value="{{ data_get($row, 'income_source_id') }}"><input aria-label="Income source validated" name="{{ $prefix }}[source_name]" value="{{ data_get($row, 'source_name') }}" class="ui-control"><input type="hidden" name="{{ $prefix }}[source_type]" value="{{ data_get($row, 'source_type') }}"><input type="hidden" name="{{ $prefix }}[validation_status]" value="{{ data_get($row, 'validation_status') }}"><input type="hidden" name="{{ $prefix }}[monthly_amount]" value="{{ data_get($row, 'monthly_amount') }}"></td><td><div class="space-y-1 text-xs">@foreach(['existing_strong_capacity'=>'EXISTING WITH STRONG CAPACITY','existing_weak_capacity'=>'EXISTING BUT WEAK CAPACITY','not_validated'=>'WAS NOT / CANNOT BE VALIDATED'] as $value=>$label)<label class="flex items-start gap-1.5"><input type="radio" name="{{ $prefix }}[stability_result]" value="{{ $value }}" @checked(data_get($row, 'stability_result') === $value) class="mt-0.5 size-3.5">{{ $label }}</label>@endforeach</div></td><td><textarea aria-label="Key information" name="{{ $prefix }}[key_information]" rows="3" class="ui-control">{{ data_get($row, 'key_information') }}</textarea></td>
@endif
<td class="cibi-entry-action-cell"><button type="button" class="cibi-remove-entry-button" title="Remove entry" aria-label="Remove entry" data-repeater-remove><x-ui.icon name="trash" size="size-5" /></button></td></tr>
